# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and Deploy staging branch

on:
  push:
    branches:
      - staging
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '16.x'

      - name: Set up variables
        uses: microsoft/variable-substitution@v1
        with:
          files: '.env-example.json'
        env:
          API_URL: ${{ secrets.STAGING_API_URL }}
          BASE_URL: ${{ secrets.STAGING_BASE_URL }}
          CDN_URL: ${{ secrets.STAGING_CDN_URL }}

      - name: Install, eslint, and build
        run: |
          npm install yarn
          yarn install
          yarn husky
          yarn build:staging

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v3
        with:
          name: node-app
          path: dist

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'staging'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v2
        with:
          name: node-app

      - name: 'Deploy to Azure Web App'
        uses: azure/webapps-deploy@v2
        id: deploy-to-webapp
        with:
          app-name: 'tango59'
          slot-name: 'staging'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_17746ED3853A43AF825FF113859C878B }}
          package: .
